class FakesUrl {
  static const List<String> fakeUrls = [
    //0
    'https://m.media-amazon.com/images/M/MV5BMDQ2ZmE2NTMtZDE3NC00YzFjLWJhNmEtMDEzMTI5ZjU2ZGM0XkEyXkFqcGdeQXVyNTkzNDQ4ODc@._V1_FMjpg_UX300_.jpg',
    //1
    'https://m.media-amazon.com/images/M/MV5BYTcxYTA0MjAtYzdjNC00ZmFmLTgwYWItMmVhYTY5ZGZhOWQzXkEyXkFqcGdeQXVyMTAyOTE2ODg0._V1_FMjpg_UX757_.jpg',
    //2
    'https://m.media-amazon.com/images/M/MV5BZjgwNzE5ODgtYzAyZC00YTZhLThhNDktMDVlOGNhYzk5NTVkXkEyXkFqcGdeQXVyMTAzMDM4MjM0._V1_.jpg',
    //3
    'https://m.media-amazon.com/images/M/MV5BYjAxOGE2YmEtZjc4MS00ZjcxLWI5NTMtNDA2ZGU5ODQ4NTBmXkEyXkFqcGdeQXVyMTYzMDM0NTU@._V1_.jpg',
    //4
    'https://m.media-amazon.com/images/M/MV5BOGM2M2Q0ZWQtZjc5NC00NDY4LWIxYTktMDE4ZjIyYTRlNTIyXkEyXkFqcGdeQXVyODc0OTEyNDU@._V1_.jpg',
    //5
    'https://m.media-amazon.com/images/M/MV5BYjM5ZjYxNjQtZjdhYi00NzBiLTgyNGItOGU3YTYwYWE0NmEzXkEyXkFqcGdeQXVyMTAzMDM4MjM0._V1_FMjpg_UY474_.jpg',
    //6
    'https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg',
    //7
    'https://m.media-amazon.com/images/M/MV5BODM5ODQxYWYtYjViYy00ZTYzLWI2YmQtZDMyYzUzZDE5M2M4XkEyXkFqcGdeQXVyMTAzMDM4MjM0._V1_.jpg',
    //8
    'https://m.media-amazon.com/images/M/MV5BYTY3M2NhODAtMTRiNC00OThlLTg3YTAtNjIwNjU2Zjg1MDFhXkEyXkFqcGdeQXVyMTAyOTE2ODg0._V1_.jpg',
    //9
    'https://m.media-amazon.com/images/M/MV5BN2RiMTA1ZGQtOTNhYi00MjQyLTk0MzAtMWE1OTM2NWUxNzBkXkEyXkFqcGdeQXVyMTAzMDM4MjM0._V1_.jpg',
    //10
    'https://m.media-amazon.com/images/M/MV5BNDVhNjJlZmMtODJhOS00OWE4LTgxMzAtNjVlMzI0ZjI0OTMzXkEyXkFqcGdeQXVyMTAzMDM4MjM0._V1_.jpg',
    //11
    'https://m.media-amazon.com/images/M/MV5BM2E1ZjEyYWQtMjgyMy00ZTkwLThkM2QtN2YwM2NmYzAyYjE0XkEyXkFqcGdeQXVyMTAzMDM4MjM0._V1_.jpg',
    //12
    'https://m.media-amazon.com/images/M/MV5BY2QzYTNmN2QtMmM3MC00NWRhLThiOWYtZGJkMTEyMjI3YTkxXkEyXkFqcGdeQXVyMTAyOTE2ODg0._V1_.jpg',
    //13
    'https://m.media-amazon.com/images/M/MV5BMGFkNWI4MTMtNGQ0OC00MWVmLTk3MTktOGYxN2Y2YWVkZWE2XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg',
    //14
    'https://m.media-amazon.com/images/M/MV5BODRmNWRiYmUtNGM2Yy00NTgwLTgxNzMtMGExYzI5NjllNjBhXkEyXkFqcGdeQXVyMTAzMDM4MjM0._V1_.jpg',
    //15
    'https://m.media-amazon.com/images/M/MV5BYWVlMjUwMzEtMWQyZS00OGFjLWI4ZTQtYWVjYTE0NGE5NzFmXkEyXkFqcGdeQXVyNTE4Mzg5MDY@._V1_.jpg',
    //16
    'https://m.media-amazon.com/images/M/MV5BYWYwNWY0ZjMtYzUxZS00ODI3LTllNzctODNiNjhlNjcyNWM0XkEyXkFqcGdeQXVyMjcwMzM0OTI@._V1_.jpg',
    //17
    'https://m.media-amazon.com/images/M/MV5BYjBlZjA2OTctZjVjMS00YzYzLTk3NDYtNjc4ZWVmNzQyNjZkXkEyXkFqcGdeQXVyMTAyOTE2ODg0._V1_.jpg',
    //18
    'https://m.media-amazon.com/images/M/MV5BNDU1OWExYjYtOTZlMy00MWY5LThkOGMtZjBhNDdiYTY4YTM0XkEyXkFqcGdeQXVyMTAyOTE2ODg0._V1_.jpg',
    //19
    'https://m.media-amazon.com/images/M/MV5BM2FhYjEyYmYtMDI1Yy00YTdlLWI2NWQtYmEzNzAxOGY1NjY2XkEyXkFqcGdeQXVyNTA3NTIyNDg@._V1_.jpg',
  ];
}
